[profile.default]
src = "src"
out = "out"
libs = ["lib"]
fs_permissions = [{ access = "read-write", path = "./" }]
solc = "0.8.27"
via-ir = true
optimizer = true
optimizer_runs = 200

remappings = [
    "@createx/=lib/createx/",
    "@interop/=lib/interop-lib/src/",

    "@othentic-core-contracts/=lib/othentic-core-contracts/src/",
    "@layer-zero/=lib/othentic-core-contracts/lib/LayerZero-v2/packages/layerzero-v2/evm/",

    "@eigenlayer-middleware/=lib/othentic-core-contracts/lib/eigenlayer-middleware/src/",
    "@eigenlayer-contracts/=lib/othentic-core-contracts/lib/eigenlayer-contracts/src/contracts/",
    
    "@openzeppelin/=lib/othentic-core-contracts/lib/openzeppelin-contracts/",
    "@openzeppelin-contracts/=lib/othentic-core-contracts/lib/openzeppelin-contracts/",
    "@openzeppelin-upgrades/=lib/othentic-core-contracts/lib/openzeppelin-contracts-upgradeable/",
    
    "forge-std/=lib/othentic-core-contracts/lib/forge-std/src/",

    "@layerzerolabs/lz-evm-protocol-v2/=lib/layerzero-v2/packages/layerzero-v2/evm/protocol/",
    "@layerzero-v2/=lib/layerzero-v2/packages/layerzero-v2/evm/"
]

[rpc_endpoints]
mainnet = "${MAINNET_RPC_URL}"
holesky = "${HOLESKY_RPC_URL}"
sepolia = "${SEPOLIA_RPC_URL}"
anvil = "${ANVIL_RPC_URL}"
op_sepolia = "${OPSEPOLIA_RPC}"
base_sepolia = "${BASE_SEPOLIA_RPC}"
arbitrum_sepolia = "${ARBITRUM_SEPOLIA_RPC}"
arbitrum = "${ARBITRUM_RPC}"


[fmt]
bracket_spacing = false
int_types = "long"
line_length = 100
multiline_func_header = "params_first"
number_underscore = "thousands"
quote_style = "double"
tab_width = 4